server {
    listen 80;
    server_name hufsstore.shop;
    # 예시) server_name meotsa.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # HTTP → HTTPS 리다이렉트
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name hufsstore.shop;
    # 예시) server_name meotsa.com;

    ssl_certificate /etc/letsencrypt/live/hufsstore.shop/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/hufsstore.shop/privkey.pem;

    location / {
        proxy_pass http://web:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /static {
        alias /static;
    }

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
}